# Generated by Django 6.0.1 on 2026-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripcion')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptors',
                'ordering': ['-creado'],
            },
        ),
    ]
