# Generated by Django 6.0.1 on 2026-01-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'ordering': ['-creado'], 'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
    ]
