# Generated by Django 6.0.1 on 2026-01-27 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Se genera del titulo', unique=True)),
                ('contenido', models.TextField(verbose_name='Contenido del articulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publico', 'Publicado')], default='borrador', verbose_name='Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
