# Generated by Django 6.0.1 on 2026-01-27 01:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido del articulo'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera del titulo automaticamente', unique=True),
        ),
    ]
