# Generated by Django 6.0.1 on 2026-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_publicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
