# Generated by Django 6.0.1 on 2026-02-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categoria_publicacion_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Notificado por correo'),
        ),
    ]
